-- Generated by generate_flink_models.py from pipelines/inventory.json.
-- Do not edit; rerun: python3 generate_flink_models.py

{{ config(
    materialized='ephemeral',
    tags=['flink', 'raw', 'ddl'],
    meta={
        'flink': true,
        'inventory_key': 'hc_raw_device_metrics',
        'layer': 'raw',
        'statement_kind': 'ddl',
        'deploy_sequence': 1,
        'statement_name': 'hc-ddl-hc-raw-device-metrics'
    },
) }}
CREATE TABLE IF NOT EXISTS hc_raw_device_metrics (
  device_id       STRING NOT NULL COMMENT 'Device identifier',
  patient_id      STRING NOT NULL COMMENT 'Patient identifier',
  ts              TIMESTAMP(0) NOT NULL COMMENT 'Event time (second precision)',
  metric_name     STRING NOT NULL COMMENT 'e.g. Pressure, FlowRate, FlowLevel',
  metric_value    DOUBLE NOT NULL COMMENT 'Observed value',
  software_version STRING COMMENT 'Firmware/software version (debugging)',
  PRIMARY KEY (device_id, metric_name) NOT ENFORCED,
  WATERMARK FOR ts AS ts - INTERVAL '5' SECOND
) DISTRIBUTED BY HASH(device_id) INTO 1 BUCKETS
WITH (
  'changelog.mode' = 'append',
  'key.avro-registry.schema-context' = '.flink-dev',
  'value.avro-registry.schema-context' = '.flink-dev',
  'key.format' = 'avro-registry',
  'value.format' = 'avro-registry',
  'kafka.retention.time' = '0',
  'kafka.producer.compression.type' = 'snappy',
  'scan.bounded.mode' = 'unbounded',
  'scan.startup.mode' = 'earliest-offset',
  'value.fields-include' = 'all'
);
