#!/usr/bin/env python3
"""
Regenerate models/flink/{raw,rmd}/*.sql from pipelines/inventory.json.

Each inventory table produces two dbt models (DDL then DML) with meta used by
dbt_flink_deploy.py after `dbt compile`. Run from this directory:

  python3 generate_flink_models.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PIPELINES_DIR = SCRIPT_DIR.parent
REPO_ROOT = PIPELINES_DIR.parent
INV_PATH = PIPELINES_DIR / "inventory.json"
OUT_BASE = SCRIPT_DIR / "models" / "flink"

HEADER = (
    "-- Generated by generate_flink_models.py from pipelines/inventory.json.\n"
    "-- Do not edit; rerun: python3 generate_flink_models.py\n\n"
)


def _meta_jinja(
    *,
    table: str,
    layer: str,
    kind: str,
    seq: int,
    stmt: str,
    dml_ref: str | None,
) -> str:
    parts = [
        "'flink': true",
        f"'inventory_key': '{table}'",
        f"'layer': '{layer}'",
        f"'statement_kind': '{kind}'",
        f"'deploy_sequence': {seq}",
        f"'statement_name': '{stmt}'",
    ]
    if dml_ref is not None:
        parts.append(f"'dml_ref': '{dml_ref}'")
    inner = ",\n        ".join(parts)
    return f"""{{{{ config(
    materialized='ephemeral',
    tags=['flink', '{layer}', '{kind}'],
    meta={{
        {inner}
    }},
) }}}}"""


def main() -> None:
    inv = json.loads(INV_PATH.read_text(encoding="utf-8"))
    seq = 0

    for layer in ("raw", "rmd"):
        layer_dir = OUT_BASE / layer
        layer_dir.mkdir(parents=True, exist_ok=True)
        for old in layer_dir.glob("flink__*.sql"):
            old.unlink()

        for _inv_key, item in inv.items():
            if item["product_name"] != layer:
                continue
            table = item["table_name"]
            for kind, ref_field in (("ddl", "ddl_ref"), ("dml", "dml_ref")):
                ref = item[ref_field]
                seq += 1
                full_sql = REPO_ROOT / ref
                if not full_sql.exists():
                    print(f"Missing SQL file: {full_sql}", file=sys.stderr)
                    sys.exit(1)
                body = full_sql.read_text(encoding="utf-8")
                stmt = f"hc-{kind}-{table.replace('_', '-')}"
                dml_meta = ref if kind == "dml" else None
                model_name = f"flink__{table}__{kind}"
                content = HEADER + _meta_jinja(
                    table=table,
                    layer=layer,
                    kind=kind,
                    seq=seq,
                    stmt=stmt,
                    dml_ref=dml_meta,
                )
                content += "\n" + body.rstrip() + "\n"
                out_path = layer_dir / f"{model_name}.sql"
                out_path.write_text(content, encoding="utf-8")
                print(f"Wrote {out_path.relative_to(SCRIPT_DIR)}")

    print(f"Done. {seq} models (deploy_sequence 1..{seq}).")


if __name__ == "__main__":
    main()
