-- Generated by generate_flink_models.py from pipelines/inventory.json.
-- Do not edit; rerun: python3 generate_flink_models.py

{{ config(
    materialized='ephemeral',
    tags=['flink', 'rmd', 'dml'],
    meta={
        'flink': true,
        'inventory_key': 'hc_fct_telemetry_1h',
        'layer': 'rmd',
        'statement_kind': 'dml',
        'deploy_sequence': 14,
        'statement_name': 'hc-dml-hc-fct-telemetry-1h',
        'dml_ref': 'pipelines/rmd/hc_fct_telemetries/sql-scripts/dml.hc_fct_telemetry_1h.sql'
    },
) }}
-- 1-hour tumbling window: aggregates per device/patient/metric.
-- Uses processing-time windowing so no watermark is required on the source.
INSERT INTO hc_fct_telemetry_1h
SELECT
  window_start,
  window_end,
  device_id,
  patient_id,
  metric_name,
  AVG(metric_value)  AS avg_value,
  MIN(metric_value)  AS min_value,
  MAX(metric_value)  AS max_value,
  COUNT(*)           AS count_reading
FROM
  table (
      TUMBLE(
        TABLE hc_raw_device_metrics,
        DESCRIPTOR(ts),
        INTERVAL '1' HOUR
      )
  )
group by window_start, window_end, device_id, patient_id, metric_name;
