-- Generated by generate_flink_models.py from pipelines/inventory.json.
-- Do not edit; rerun: python3 generate_flink_models.py

{{ config(
    materialized='ephemeral',
    tags=['flink', 'rmd', 'dml'],
    meta={
        'flink': true,
        'inventory_key': 'hc_src_patients',
        'layer': 'rmd',
        'statement_kind': 'dml',
        'deploy_sequence': 18,
        'statement_name': 'hc-dml-hc-src-patients',
        'dml_ref': 'pipelines/rmd/src_patients/sql-scripts/dml.src_patients.sql'
    },
) }}
INSERT INTO hc_src_patients
WITH normalized AS (
  SELECT
    coalesce(if(op = 'd', json_value(before, '$.patient_id'), json_value(after, '$.patient_id') ), 'dummy_patient_id') AS patient_id,
    coalesce(if(op = 'd', json_value(before, '$.name'), json_value(after, '$.name')), 'dummy_name') AS name,
    coalesce(if(op = 'd', json_value(before, '$.gender'), json_value(after, '$.gender')), 'dummy_gender') AS gender,
    coalesce(if(op = 'd', json_value(before, '$.birth_date'), json_value(after, '$.birth_date')), 'dummy_birth_date') AS birth_date,
    coalesce(if(op = 'd', json_value(before, '$.zip_code'), json_value(after, '$.zip_code')), 'dummy_zip_code') AS zip_code,
    source_ts_ms,
    op
  FROM hc_raw_patients
),
deduped AS (
  SELECT
    patient_id,
    name,
    gender,
    birth_date,
    zip_code,
    source_ts_ms,
    op,
    ROW_NUMBER() OVER (PARTITION BY patient_id ORDER BY source_ts_ms ASC) AS rn
  FROM normalized
)

SELECT patient_id, name, gender, birth_date, zip_code, source_ts_ms, op
FROM deduped
WHERE rn = 1
