-- Generated by generate_flink_models.py from pipelines/inventory.json.
-- Do not edit; rerun: python3 generate_flink_models.py

{{ config(
    materialized='ephemeral',
    tags=['flink', 'rmd', 'dml'],
    meta={
        'flink': true,
        'inventory_key': 'hc_src_devices',
        'layer': 'rmd',
        'statement_kind': 'dml',
        'deploy_sequence': 16,
        'statement_name': 'hc-dml-hc-src-devices',
        'dml_ref': 'pipelines/rmd/src_devices/sql-scripts/dml.src_devices.sql'
    },
) }}
INSERT INTO hc_src_devices
SELECT 
    device_id,
    patient_id,
    model_type,
    manufacturer,
    serial_number,
    software_version,
    pressure_setting,
    flow_rate_setting,
    flow_level_setting
FROM hc_raw_devices
WHERE patient_id IS NOT NULL
