-- Generated by generate_flink_models.py from pipelines/inventory.json.
-- Do not edit; rerun: python3 generate_flink_models.py

{{ config(
    materialized='ephemeral',
    tags=['flink', 'rmd', 'ddl'],
    meta={
        'flink': true,
        'inventory_key': 'hc_src_devices',
        'layer': 'rmd',
        'statement_kind': 'ddl',
        'deploy_sequence': 15,
        'statement_name': 'hc-ddl-hc-src-devices'
    },
) }}
CREATE TABLE IF NOT EXISTS hc_src_devices (
  device_id          STRING NOT NULL COMMENT 'Primary key',
  patient_id         STRING NOT NULL COMMENT 'Patient identifier',
  model_type         STRING COMMENT 'Model type',
  manufacturer       STRING COMMENT 'Manufacturer',
  serial_number      STRING COMMENT 'Serial number',
  software_version   STRING COMMENT 'Software version',
  pressure_setting   DOUBLE COMMENT 'Pressure setting',
  flow_rate_setting  DOUBLE COMMENT 'Flow rate setting',
  flow_level_setting INT COMMENT 'Flow level',
  PRIMARY KEY (patient_id, device_id) NOT ENFORCED
) DISTRIBUTED BY HASH(patient_id, device_id) INTO 2 BUCKETS
WITH (
  'changelog.mode' = 'upsert',
  'key.avro-registry.schema-context' = '.flink-dev',
  'value.avro-registry.schema-context' = '.flink-dev',
  'key.format' = 'avro-registry',
  'value.format' = 'avro-registry',
  'kafka.retention.time' = '0',
  'kafka.producer.compression.type' = 'snappy',
  'scan.bounded.mode' = 'unbounded',
  'scan.startup.mode' = 'earliest-offset',
  'value.fields-include' = 'all'
);
